using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace ZiyaretciDefteri
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
        }



        private void btnKayıt_Click(object sender, EventArgs e)
        {
            string DByolu = "Server=BULAT;Database=ZiyaretciDefter;Uid=sa;Password=12;";

            SqlConnection con = new SqlConnection(DByolu);

            
                if (con.State == ConnectionState.Closed)
                {
                    con.Open();
                }

                string Reg = "insert into ZiyaretciDefteri(ZiyaretciAdı," +
                    "ZiyaretciSoyadı" +
                    ",ZiyaretciFirm," +
                    "ZiyaretciÜnv," +
                    "ZiyaretciHES," +
                    "Ziyaretciİrsaliye," +
                    "ZiyaretciİrsTeslim," +
                    "ZiyaretciİrsTeslimEden," +
                    "ZiyaretciArac," +
                    "ZiyaretciKonu," +
                    "ZiyaretciPlanlımı" +
                    ",ZiyaretciTarih," +
                    "ZiyaretciBaşlangıç" +
                    ",ZiyaretciBitiş," +
                    "ZiyaretEdilenPersKod," +
                    "ZiyaretEdilenAdıSoyadı," +
                    "GirisYapanPers," +
                    "ZiyaretEdilenGirisKapı," +
                    "ZiyaretEdilenTarih," +
                    "ZiyaretEdilenSaat) " +
                    "values (@ZiyaretciAdı," +
                    "@ZiyaretciSoyadı," +
                    "@ZiyaretciFirm," +
                    "@ZiyaretciÜnv," +
                    "@ZiyaretciHES," +
                    "@Ziyaretciİrsaliye," +
                    "@ZiyaretciİrsTeslim," +
                    "@ZiyaretciİrsTeslimEden," +
                    "@ZiyaretciArac," +
                    "@ZiyaretciKonu," +
                    "@ZiyaretciPlanlımı," +
                    "@ZiyaretciTarih," +
                    "@ZiyaretciBaşlangıç," +
                    "@ZiyaretciBitiş," +
                    "@ZiyaretEdilenPersKod," +
                    "@ZiyaretEdilenAdıSoyadı," +
                    "@GirisYapanPers," +
                    "@ZiyaretEdilenGirisKapı," +
                    "@ZiyaretEdilenTarih," +
                    "@ZiyaretEdilenSaat)";

                SqlCommand cmd = new SqlCommand(Reg,con);

                cmd.Parameters.AddWithValue("@ZiyaretciAdı", txtAdı.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciSoyadı", txtSoyadı.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciFirm", txtÇalFirm.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciÜnv", txtÜnv.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciHES", txtHES.Text);
                cmd.Parameters.AddWithValue("@Ziyaretciİrsaliye", txtİrsal.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciİrsTeslim", txtİrTes.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciİrsTeslimEden", txtİrTesEden.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciArac", txtAraçPlaka.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciKonu", txtKonu.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciPlanlımı", cmbPlanlımı.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciTarih", dateTimePicker1.Value);
                cmd.Parameters.AddWithValue("@ZiyaretciBaşlangıç", txtBaşlama.Text);
                cmd.Parameters.AddWithValue("@ZiyaretciBitiş", txtBitiş.Text);
                cmd.Parameters.AddWithValue("@ZiyaretEdilenPersKod", txtPersKod.Text);
                cmd.Parameters.AddWithValue("@ZiyaretEdilenAdıSoyadı", txtAdıSoyadı.Text);
                cmd.Parameters.AddWithValue("@GirisYapanPers", txtZiyPers.Text);
                cmd.Parameters.AddWithValue("@ZiyaretEdilenGirisKapı", cmbGiriş.Text);
                cmd.Parameters.AddWithValue("@ZiyaretEdilenTarih", dateTimePicker1.Value);
                cmd.Parameters.AddWithValue("@ZiyaretEdilenSaat", timeEdit3.EditValue);

                cmd.ExecuteNonQuery();
                con.Close();





            SqlConnection con1 = new SqlConnection("Server=BULAT;Database=ZiyaretciDefter;Uid=sa;Password=12;");
            SqlCommand com = new SqlCommand("Select top(1) ID from ZiyaretciDefteri order by ID desc", con1);
            con1.Open();
            SqlDataReader dr = com.ExecuteReader();
            if (dr.Read())
            {
                label2.Text = dr["ID"].ToString();
            }
            con1.Close();

            ClearTexts();


        }


        private void btnBul_Click(object sender, EventArgs e)
        {
            int ID = 0;
            if (int.TryParse(txtBul.Text, out ID))
            {
                SqlConnection cnn = new SqlConnection("Server=BULAT;Database=ZiyaretciDefter;Uid=sa;Password=12;");
                SqlCommand cmd = new SqlCommand("select * from ZiyaretciDefteri where id = @ID", cnn);
                cmd.Parameters.AddWithValue("@ID", ID);
                cnn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    txtAdı.Text += dr["ZiyaretciAdı"].ToString();
                    txtSoyadı.Text += dr["ZiyaretciSoyadı"].ToString();
                    txtÇalFirm.Text += dr["ZiyaretciFirm"].ToString();
                    txtAraçPlaka.Text += dr["ZiyaretciArac"].ToString();
                    txtHES.Text += dr["ZiyaretciHES"].ToString();
                    txtKonu.Text += dr["ZiyaretciKonu"].ToString();
                    txtPersKod.Text += dr["ZiyaretEdilenPersKod"].ToString();
                    txtZiyPers.Text += dr["GirisYapanPers"].ToString();
                    txtÜnv.Text += dr["ZiyaretciÜnv"].ToString();
                    txtİrsal.Text += dr["Ziyaretciİrsaliye"].ToString();
                    txtİrTes.Text += dr["ZiyaretciİrsTeslim"].ToString();
                    txtİrTesEden.Text += dr["ZiyaretciİrsTeslimEden"].ToString();
                    cmbGiriş.Text += dr["ZiyaretEdilenGirisKapı"].ToString();
                    cmbPlanlımı.Text += dr["ZiyaretciPlanlımı"].ToString();
                    txtBaşlama.Text += System.Convert.ToDateTime(dr["ZiyaretciBaşlangıç"].ToString());
                    txtBitiş.Text += System.Convert.ToDateTime(dr["ZiyaretciBitiş"].ToString());
                    timeEdit3.Text += System.Convert.ToDateTime(dr["ZiyaretEdilenSaat"].ToString());

                }
                cnn.Close();

            }


        }


        private void btnUpdate_Click(object sender, EventArgs e)
        {
            string DByolu = "Server=BULAT;Database=ZiyaretciDefter;Uid=sa;Password=12;";

            SqlConnection con = new SqlConnection(DByolu);
            con.Open();

            string Reg = "update ZiyaretciDefteri set" +
                " ZiyaretciAdı=@ZiyaretciAdı," +
                "ZiyaretciSoyadı=@ZiyaretciSoyadı," +
                "ZiyaretciFirm=@ZiyaretciFirm," +
                "ZiyaretciÜnv=@ZiyaretciÜnv," +
                "ZiyaretciHES=@ZiyaretciHES," +
                "Ziyaretciİrsaliye=@Ziyaretciİrsaliye," +
                "ZiyaretciİrsTeslim=@ZiyaretciİrsTeslim," +
                "ZiyaretciİrsTeslimEden=@ZiyaretciİrsTeslimEden," +
                "ZiyaretciArac=@ZiyaretciArac," +
                "ZiyaretciKonu=@ZiyaretciKonu," +
                "ZiyaretciPlanlımı=@ZiyaretciPlanlımı," +
                "ZiyaretciTarih=@ZiyaretciTarih," +
                "ZiyaretciBaşlangıç=@ZiyaretciBaşlangıç," +
                "ZiyaretciBitiş=@ZiyaretciBitiş," +
                "ZiyaretEdilenPersKod=@ZiyaretEdilenPersKod," +
                "ZiyaretEdilenAdıSoyadı=@ZiyaretEdilenAdıSoyadı," +
                "GirisYapanPers=@GirisYapanPers," +
                "ZiyaretEdilenGirisKapı=@ZiyaretEdilenGirisKapı," +
                "ZiyaretEdilenTarih=@ZiyaretEdilenTarih," +
                "ZiyaretEdilenSaat=@ZiyaretEdilenSaat" +
                " where ID=@ID";
            // müşteriler tablomuzun ilgili alanlarını değiştirecek olan güncelleme sorgusu.
            SqlCommand cmd = new SqlCommand(Reg, con);
            //Sorgumuzu ve baglantimizi parametre olarak alan bir SqlCommand nesnesi oluşturuyoruz.


            cmd.Parameters.AddWithValue("@ZiyaretciAdı", txtAdı.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciSoyadı", txtSoyadı.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciFirm", txtÇalFirm.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciÜnv", txtÜnv.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciHES", txtHES.Text);
            cmd.Parameters.AddWithValue("@Ziyaretciİrsaliye", txtİrsal.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciİrsTeslim", txtİrTes.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciİrsTeslimEden", txtİrTesEden.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciArac", txtAraçPlaka.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciKonu", txtKonu.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciPlanlımı", cmbPlanlımı.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciTarih", dateTimePicker1.Value);
            cmd.Parameters.AddWithValue("@ZiyaretciBaşlangıç", txtBaşlama.Text);
            cmd.Parameters.AddWithValue("@ZiyaretciBitiş", txtBitiş.Text);
            cmd.Parameters.AddWithValue("@ZiyaretEdilenPersKod", txtPersKod.Text);
            cmd.Parameters.AddWithValue("@ZiyaretEdilenAdıSoyadı", txtAdıSoyadı.Text);
            cmd.Parameters.AddWithValue("@GirisYapanPers", txtZiyPers.Text);
            cmd.Parameters.AddWithValue("@ZiyaretEdilenGirisKapı", cmbGiriş.Text);
            cmd.Parameters.AddWithValue("@ZiyaretEdilenTarih", dateTimePicker1.Value);
            cmd.Parameters.AddWithValue("@ZiyaretEdilenSaat", timeEdit3.EditValue);
            cmd.Parameters.AddWithValue("@ID", txtBul.Text);


            cmd.ExecuteNonQuery();

            con.Close();

            MessageBox.Show("Müşteri Bilgileri Güncellendi.");

            ClearTexts();


        }


        private void button1_Click(object sender, EventArgs e)
        {
            ŞimdikiSaat();
        }


        private void btnRefresh_Click(object sender, EventArgs e)
        {
            sqlDataSource3.FillAsync();

            ClearTexts();

        }


        private void ClearTexts()
        {
            txtAdı.Clear();
            txtSoyadı.Clear();
            txtÇalFirm.Clear();
            txtAraçPlaka.Clear();
            txtBul.Clear();
            txtHES.Clear();
            txtKonu.Clear();
            txtPersKod.Clear();
            txtZiyPers.Clear();
            txtÜnv.Clear();
            txtİrsal.Clear();
            txtİrTes.Clear();
            txtİrTesEden.Clear();
            cmbGiriş.Text = "";
            cmbPlanlımı.Text = "";
            label2.Text = "";
            txtBaşlama.Text = "";
            txtBitiş.Text = "";
            timeEdit3.Time = System.Convert.ToDateTime("00:00:00");
        }


        private void ŞimdikiSaat()
        {
            DateTime dt = new DateTime();

            dt = DateTime.Now;

            dt = dt.AddHours(1);

            txtBaşlama.Text = DateTime.Now.ToLongTimeString();

            txtBitiş.Text = dt.ToLongTimeString();


            
        }


        private void SaatEkle_Click(object sender, EventArgs e)
        {
            DateTime dt = new DateTime();
            dt = Convert.ToDateTime(txtBitiş.Text);
            dt = dt.AddHours(1);
            txtBitiş.Text = dt.ToLongTimeString();
        }


        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            //DataRow dr = gridView2.GetDataRow(gridView2.FocusedRowHandle);

            //if (dr != null)
            //{
            //    txtAdı.Text = dr["ZiyaretciAdı"].ToString();
            //    txtSoyadı.Text = dr["ZiyaretciSoyadı"].ToString();
            //    txtÇalFirm.Text = dr["ZiyaretciFirm"].ToString();
            //    txtAraçPlaka.Text = dr["ZiyaretciArac"].ToString();
            //    txtHES.Text = dr["ZiyaretciHES"].ToString();
            //    txtKonu.Text = dr["ZiyaretciKonu"].ToString();
            //    txtPersKod.Text = dr["ZiyaretEdilenPersKod"].ToString();
            //    txtZiyPers.Text = dr["GirisYapanPers"].ToString();
            //    txtÜnv.Text = dr["ZiyaretciÜnv"].ToString();
            //    txtİrsal.Text = dr["Ziyaretciİrsaliye"].ToString();
            //    txtİrTes.Text = dr["ZiyaretciİrsTeslim"].ToString();
            //    txtİrTesEden.Text = dr["ZiyaretciİrsTeslimEden"].ToString();
            //    cmbGiriş.Text = dr["ZiyaretEdilenGirisKapı"].ToString();
            //    cmbPlanlımı.Text = dr["ZiyaretciPlanlımı"].ToString();
            //    txtBaşlama.Text = (dr["ZiyaretciBaşlangıç"].ToString());
            //    txtBitiş.Text = (dr["ZiyaretciBitiş"].ToString());
            //    timeEdit3.Text = (dr["ZiyaretEdilenSaat"].ToString());
            //}
        }
    }
}
